/*
 * File: app/store/CourseStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.store.CourseStore', {
    extend: 'Ext.data.Store',
    alias: 'store.coursestore',

    requires: [
        'StudentManagementSystem.model.CourseModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CourseStore',
            model: 'StudentManagementSystem.model.CourseModel',
            data: [
                {
                    id: 1,
                    lesId: 'CENG1001',
                    lesClass: '1',
                    lesName: 'General Physics II/Lab',
                    lesCredit: '6',
                    lesTeacher: 'Prof. Dr. Murat BAYHAN',
                    lesInfo: 'Fizik maddeyi, maddenin uzay-zamanda hareketini enerji ve kuvveti de kapsamak üzere bütün ilgili kavramlarla birlikte inceleyen doğa bilimidir.Daha genel olarak, evren ile ilgili nasılları cevaplamak için doğanın genel bir analizidir.'
                },
                {
                    id: 2,
                    lesId: 'CENG1002',
                    lesClass: '1',
                    lesName: 'Calculus II',
                    lesCredit: '6',
                    lesTeacher: 'Assist. Prof. Dr. M. Ali BALCI',
                    lesInfo: 'Matematik, nicelik, yapı, uzay ve değişim gibi konularla ilgilenir.Matematikçiler ve filozoflar arasında matematiğin kesin kapsamı ve tanımı konusunda görüş ayrılığı vardır.'
                },
                {
                    id: 3,
                    lesId: 'CENG1003',
                    lesClass: '1',
                    lesName: 'Introduction to Object Oriented Programming',
                    lesCredit: '6',
                    lesTeacher: 'Assist. Prof. Dr. Özgür KILIÇ',
                    lesInfo: 'Nesne tabanlı programlama dili, nesne kullanımını destekleyen ve sarma ilkesine uyan programlama dillerini tanımlar.Ancak nesne tabanlı programlama dilleri, kalıtım gibi nesne yönelimli programlama dillerine özel özellikleri taşımazlar.Bu durumda nesne tabanlı programlama dilleri nesne yönelimli programlama dillerinin altkümesini oluşturur.'
                },
                {
                    id: 4,
                    lesId: 'CENG2001',
                    lesClass: '2',
                    lesName: 'Programming Language Concepts',
                    lesCredit: '4',
                    lesTeacher: 'Assist. Prof. Dr. İzzet PEMBECİ',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 5,
                    lesId: 'CENG2002',
                    lesClass: '2',
                    lesName: 'Database Management Systems',
                    lesCredit: '6',
                    lesTeacher: 'Assist. Prof. Dr. Tuğba Önal SÜZEK',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 6,
                    lesId: 'CENG2003',
                    lesClass: '2',
                    lesName: 'Computer Organization',
                    lesCredit: '3',
                    lesTeacher: 'Assist. Prof. Dr. Özgür KILIÇ',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 7,
                    lesId: 'CENG2004',
                    lesClass: '2',
                    lesName: 'Operating Systems',
                    lesCredit: '2',
                    lesTeacher: 'Assist. Prof. Dr. Enis KARAARSLAN',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 8,
                    lesId: 'CENG3001',
                    lesClass: '3',
                    lesName: 'Software Engineering',
                    lesCredit: '4',
                    lesTeacher: 'Assist. Prof. Dr. Barış Ethem SÜZEK',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 9,
                    lesId: 'CENG3002',
                    lesClass: '3',
                    lesName: 'Applied Machine Learning',
                    lesCredit: '6',
                    lesTeacher: 'Assist. Prof. Dr. Barış Ethem SÜZEK',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 10,
                    lesId: 'CENG3003',
                    lesClass: '3',
                    lesName: 'Natural Language Processing',
                    lesCredit: '6',
                    lesTeacher: 'Assoc. Prof. Dr. B. Taner DİNÇER',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 11,
                    lesId: 'CENG4001',
                    lesClass: '4',
                    lesName: 'Computer and Network Security III',
                    lesCredit: '6',
                    lesTeacher: 'Assist. Prof. Dr. Enis KARAARSLAN',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 12,
                    lesId: 'CENG4002',
                    lesClass: '4',
                    lesName: 'Software Validation, Verification and Testing',
                    lesCredit: '4',
                    lesTeacher: 'Prof. Dr. Fevzi BELLi',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                },
                {
                    id: 13,
                    lesId: 'CENG4003',
                    lesClass: '4',
                    lesName: 'Fundamental Image Processing',
                    lesCredit: '4',
                    lesTeacher: 'Assist. Prof. Dr. Ufuk BAL',
                    lesInfo: 'Ders bilgisi bulunamadı.'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});