/*
 * File: app/store/DepartmentStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.store.DepartmentStore', {
    extend: 'Ext.data.Store',

    requires: [
        'StudentManagementSystem.model.DepartmentModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'DepartmentStore',
            model: 'StudentManagementSystem.model.DepartmentModel',
            data: [
                {
                    dep_id: '1',
                    department: 'Resim'
                },
                {
                    dep_id: '2',
                    department: 'Heykel'
                },
                {
                    dep_id: '3',
                    department: 'Psikoloji'
                },
                {
                    dep_id: '4',
                    department: 'Sanat Tarihi'
                },
                {
                    dep_id: '5',
                    department: 'Felsefe'
                },
                {
                    dep_id: '6',
                    department: 'İlkogretim Egitimi'
                },
                {
                    dep_id: '7',
                    department: 'Yabancı Dil Egitimi'
                },
                {
                    dep_id: '8',
                    department: 'Turkce Dil Egitimi'
                },
                {
                    dep_id: '9',
                    department: 'Biyoloji'
                },
                {
                    dep_id: '10',
                    department: 'Fizik'
                },
                {
                    dep_id: '11',
                    department: 'Kimya'
                },
                {
                    dep_id: '12',
                    department: 'Ekonomi ve Finans'
                },
                {
                    dep_id: '13',
                    department: 'Turizm İşletmeciliği'
                },
                {
                    dep_id: '14',
                    department: 'İşletme'
                },
                {
                    dep_id: '15',
                    department: 'Kamu Yonetimi'
                },
                {
                    dep_id: '16',
                    department: 'Temel İslam'
                },
                {
                    dep_id: '17',
                    department: 'Felefe ve Din'
                },
                {
                    dep_id: '18',
                    department: 'İslam Tarihi'
                },
                {
                    dep_id: '19',
                    department: 'Veteriner 1'
                },
                {
                    dep_id: '20',
                    department: 'Veteriner 2'
                },
                {
                    dep_id: '21',
                    department: 'Veteriner 3'
                },
                {
                    dep_id: '22',
                    department: 'Mimarlık 1'
                },
                {
                    dep_id: '23',
                    department: 'Sehir ve Bolge Planlama'
                },
                {
                    dep_id: '24',
                    department: 'Mimarlık 2'
                },
                {
                    dep_id: '25',
                    department: 'Bilgisayar Muhendisligi'
                },
                {
                    dep_id: '26',
                    department: 'Metalurji Muhendisligi'
                },
                {
                    dep_id: '27',
                    department: 'İnsaat Muhendisligi'
                },
                {
                    dep_id: '28',
                    department: 'Beslenme ve Diyetitik'
                },
                {
                    dep_id: '29',
                    department: 'Fizyoterapi'
                },
                {
                    dep_id: '30',
                    department: 'Grafik'
                },
                {
                    dep_id: '31',
                    department: 'Tarim'
                },
                {
                    dep_id: '32',
                    department: 'Hemsirelik'
                },
                {
                    dep_id: '33',
                    department: 'Antronorluk'
                },
                {
                    dep_id: '34',
                    department: 'Rekreasyon'
                },
                {
                    dep_id: '35',
                    department: 'Spor Yoneticiligi'
                },
                {
                    dep_id: '36',
                    department: 'Su Urunleri Yetistiriciligi'
                },
                {
                    dep_id: '37',
                    department: 'Su Urunleri Avlanma'
                },
                {
                    dep_id: '38',
                    department: 'Su Urunleri Muhendisligi'
                },
                {
                    dep_id: '39',
                    department: 'Elektronik ve Bilgisayar'
                },
                {
                    dep_id: '40',
                    department: 'Mobilya Dekorasyon'
                },
                {
                    dep_id: '41',
                    department: 'Agac İsleri'
                },
                {
                    dep_id: '42',
                    department: 'Bilisim Isleri'
                },
                {
                    dep_id: '43',
                    department: 'Enerji Sistemleri'
                },
                {
                    dep_id: '44',
                    department: 'Dahili'
                },
                {
                    dep_id: '45',
                    department: 'Cerrahi'
                },
                {
                    dep_id: '46',
                    department: 'Temel Tip'
                },
                {
                    dep_id: '47',
                    department: 'Konaklama Isletmeciligi'
                },
                {
                    dep_id: '48',
                    department: 'Seyehat Isletmeciligi'
                },
                {
                    dep_id: '49',
                    department: 'Yiyecek Icecek Isletmeciligi'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});