/*
 * File: app/store/MesajStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.store.MesajStore', {
    extend: 'Ext.data.Store',

    requires: [
        'StudentManagementSystem.model.MesajModel',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MesajStore',
            model: 'StudentManagementSystem.model.MesajModel',
            data: [
                {
                    unvan: 'Prof. Dr.',
                    ad: 'İzzet Pembeci',
                    mesaj: 'Mesajınız bana ulaşmıştır teşekkürler',
                    tarih: '12/11/2016',
                    check: 0
                },
                {
                    unvan: 'Doç. Dr.',
                    ad: 'Barış Süzek',
                    mesaj: 'Mesajınız bana ulaşmıştır teşekkürler',
                    tarih: '15/11/2016',
                    check: 0
                }
            ],
            proxy: {
                type: 'jsonp',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});