/*
 * File: app/store/TeacherStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.store.TeacherStore', {
    extend: 'Ext.data.Store',

    requires: [
        'StudentManagementSystem.model.TeacherModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TeacherStore',
            model: 'StudentManagementSystem.model.TeacherModel',
            data: [
                {
                    id: '1',
                    login_id: '100',
                    name: 'Bekir Taner',
                    surname: 'Dinçer',
                    branch: 'Yr. Doç. Dr.',
                    faculty: 'Mühendislik Fakültesi'
                },
                {
                    id: '2',
                    login_id: '101',
                    name: 'İzzet',
                    surname: 'Pembeci',
                    branch: 'Doç. Dr.',
                    faculty: 'Mühendislik Fakültesi'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});