/*
 * File: app/store/TranskriptStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.store.TranskriptStore', {
    extend: 'Ext.data.Store',

    requires: [
        'StudentManagementSystem.model.TranskriptModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TranskriptStore',
            model: 'StudentManagementSystem.model.TranskriptModel',
            data: [
                {
                    harf: 'AA',
                    deger: '4'
                },
                {
                    harf: 'BA',
                    deger: '3.5'
                },
                {
                    harf: 'BB',
                    deger: '3'
                },
                {
                    harf: 'CB',
                    deger: '2.5'
                },
                {
                    harf: 'CC',
                    deger: '2'
                },
                {
                    harf: 'DC',
                    deger: '1.5'
                },
                {
                    harf: 'DD',
                    deger: '1'
                },
                {
                    harf: 'FF',
                    deger: '0'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});