/*
 * File: app/store/UserStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.store.UserStore', {
    extend: 'Ext.data.Store',
    alias: 'store.userstore',

    requires: [
        'StudentManagementSystem.model.UserModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'UserStore',
            model: 'StudentManagementSystem.model.UserModel',
            data: [
                {
                    txtId: '1',
                    txtName: 'Cihan',
                    txtSurname: 'Selim',
                    txtIdentifierNo: '5',
                    txtStudentNo: '5',
                    txtFaculty: 'Mühendislik Fakültesi',
                    txtDepartment: 'Bilgisayar Mühendisliği',
                    txtShort: 'CENG',
                    txtClass: '3',
                    txtActiveSeason: '2016-2017 Güz'
                },
                {
                    txtId: '2',
                    txtName: 'Eren',
                    txtSurname: 'Vural',
                    txtIdentifierNo: '6',
                    txtStudentNo: '6',
                    txtFaculty: 'Mühendislik Fakültesi',
                    txtDepartment: 'Bilgisayar Mühendisliği',
                    txtShort: 'CENG',
                    txtClass: '4',
                    txtActiveSeason: '2016-2017 Güz'
                },
                {
                    txtId: '4',
                    txtName: 'Muhammed Olcay',
                    txtSurname: 'Tercanlı',
                    txtIdentifierNo: '13457845442',
                    txtStudentNo: '120709041',
                    txtFaculty: 'Mühendislik Fakültesi',
                    txtDepartment: 'Bilgisayar Mühendisliği',
                    txtShort: 'CENG',
                    txtClass: '1',
                    txtActiveSeason: '2016-2017 Güz'
                },
                {
                    txtId: '5',
                    txtName: 'Mahmut',
                    txtSurname: 'Koçaker',
                    txtIdentifierNo: '98567458965',
                    txtStudentNo: '120709030',
                    txtFaculty: 'Mühendislik Fakültesi',
                    txtDepartment: 'Bilgisayar Mühendisliği',
                    txtShort: 'CENG',
                    txtClass: '2',
                    txtActiveSeason: '2016-2017 Güz'
                },
                {
                    txtId: '6',
                    txtName: 'Mert',
                    txtSurname: 'Yılmaz',
                    txtIdentifierNo: '14579687556',
                    txtStudentNo: '102070902',
                    txtFaculty: 'Enformatilk Fakültesi',
                    txtDepartment: 'Bilişim Sistemleri',
                    txtShort: 'ENF',
                    txtClass: '2',
                    txtActiveSeason: '2016-2017 Güz'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});