/*
 * File: app/view/indexPageViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.indexPageViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.indexteacherpage',

    onButNotlarClick: function(button, e, eOpts) {

        var ogrenciNotPageView = Ext.create('StudentManagementSystem.view.ogrenciNotPage',
            {
                title : ''
            }
            );

        var wind=Ext.create('Ext.Window',{
            width: 920,
            height: 350,
            itemId:'ogrenciNotPage',
            items:[ogrenciNotPageView],
            title:'ÖĞRENCİLER',
            modal:true,
            closeAction:'destroy',
            resizable:false,
            closable: true,
            draggable: false,
            listeners:{
                'close':function(win){
                    ogrenciNotPageView.close();
                }
            }
        });
        wind.show();
    },

    onButDevamsizlikClick: function(button, e, eOpts) {

        var ogrenciDevamsizlikPageView = Ext.create('StudentManagementSystem.view.ogrenciDevamsizlikPage',
            {
                title : ''
            }
            );

        var wind=Ext.create('Ext.Window',{
            width: 920,
            height: 350,
            itemId:'ogrenciDevamsizlikPage',
            items:[ogrenciDevamsizlikPageView],
            title:'ÖĞRENCİLER',
            modal:true,
            closeAction:'destroy',
            resizable:false,
            closable: true,
            draggable: false,
            listeners:{
                'close':function(win){
                    ogrenciDevamsizlikPageView.close();
                }
            }
        });
        wind.show();
    },

    onMesajGonderOgretmenClick: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();

        var mesajGonderOgretmenPageView = Ext.create('StudentManagementSystem.view.mesajGonderOgretmenPage',
            {
                title : ''
                //class_no : refs.txtClass.getValue()
            }
            );

        var wind=Ext.create('Ext.Window',{
            width: 557,
            height: 346,
            itemId:'mesajGonderOgretmenPage',
            items:[mesajGonderOgretmenPageView],
            title:'MESAJ',
            modal:true,
            closeAction:'destroy',
            resizable:false,
            closable: true,
            draggable: false,
            listeners:{
                'close':function(win){
                    mesajGonderOgretmenPageView.close();
                }
            }
        });
        wind.show();
    },

    onButCikisClick: function(button, e, eOpts) {
        Ext.MessageBox.confirm('Çıkış', 'Emin misiniz?',function(btn){

            if(btn === 'yes'){
                location.href = 'index.html';
            }
            else{
                MessageBox.close();
            }
        });
    },

    onMytreeviewItemClick: function(dataview, record, item, index, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();

        var transkriptPageView = Ext.create('StudentManagementSystem.view.transkriptPage',
            {
                title : ''
            }
            );

        var wind=Ext.create('Ext.Window',{
            width: 990,
            height: 470,
            itemId:'transkriptPage',
            items:[transkriptPageView],
            title:'TRANSKRİPT SENARYOSU',
            modal:true,
            closeAction:'destroy',
            resizable:false,
            closable: true,
            draggable: false,
            listeners:{
                'close':function(win){
                    transkriptPageView.close();
                }
            }
        });
        wind.show();
    },

    onDersTableRowDblClick: function(tableview, record, tr, rowIndex, e, eOpts) {
        var controller = this;
        var refs = controller.getReferences();
        var myForm = new Ext.form.Panel({
            width: 400,
            height: 250,
            title: 'DERS BİLGİSİ',
            modal: true,
            floating: true,
            closable : true,
            items: [
            {
                xtype: 'container',
                flex: 0.3,
                margin: '10 0 0 5',
                layout: {
                    type: 'vbox',
                    pack: 'center'
                },
                items: [
                {
                    xtype: 'label',
                    width: 370,
                    margin: '5 0 0 0',
                    text: 'DERS KODU: ' + refs.courseList.store.data.items[rowIndex].data.lesId
                },
                {
                    xtype: 'label',
                    width: 370,
                    margin: '5 0 0 0',
                    text: 'DERS ADI: ' + refs.courseList.store.data.items[rowIndex].data.lesName
                },
                {
                    xtype: 'label',
                    width: 370,
                    margin: '5 0 0 0',
                    text: 'AKADEMİSYEN: ' + refs.courseList.store.data.items[rowIndex].data.lesTeacher
                },
                {
                    xtype: 'label',
                    width: 370,
                    margin: '5 0 0 0',
                    text: 'DERS KREDİSİ: ' + refs.courseList.store.data.items[rowIndex].data.lesCredit
                },
                {
                    xtype: 'label',
                    width: 370,
                    margin: '5 0 0 0',
                    text: 'DERS BİLGİSİ: ' + refs.courseList.store.data.items[rowIndex].data.lesInfo
                }
                ]
            }]

        });
        myForm.show();
        //Ext.MessageBox.alert(refs.courseList.store.data.items[rowIndex].data.lesName,refs.courseList.store.data.items[rowIndex].data.lesTeacher);
    },

    onIndexPageAfterRender: function(component, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        var userList = [];
        // kullanıcıları bir listeye saklar
        for (i = 0 ; i < Ext.StoreMgr.lookup("TeacherStore").data.length; i++){
            userList.push(Ext.StoreMgr.lookup("TeacherStore").data.items[i].data.login_id);
        }

        // giriş yapınca hoşgeldiniz altına isim-soyisim yazar
        if (Ext.isDefined(component.username)){

            for (k = 0; k < userList.length; k++){

                if (userList[k] === component.username){

                    refs.txtIdentifierNo.setText(Ext.StoreMgr.lookup("TeacherStore").data.items[k].data.login_id);
                    refs.txtName.setText(Ext.StoreMgr.lookup("TeacherStore").data.items[k].data.name + " " +
                    Ext.StoreMgr.lookup("TeacherStore").data.items[k].data.surname);
                    refs.txtFaculty.setText(Ext.StoreMgr.lookup("TeacherStore").data.items[k].data.faculty);
                    refs.txtDepartment.setText(Ext.StoreMgr.lookup("TeacherStore").data.items[k].data.branch);
                }
            }
        }
    }

});
