/*
 * File: app/view/loginPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.loginPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.loginpage',

    requires: [
        'StudentManagementSystem.view.loginPageViewModel',
        'StudentManagementSystem.view.loginPageViewController',
        'Ext.panel.Panel',
        'Ext.Img',
        'Ext.button.Button'
    ],

    controller: 'loginpage',
    viewModel: {
        type: 'loginpage'
    },
    reference: 'loginPage',
    border: false,
    height: 981,
    bodyStyle: 'background-image:url("img/cover.jpg")! important;\nbackground-repeat:no-repeat;',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'panel',
            border: true,
            height: 245,
            style: 'opacity:0.9;',
            width: 430,
            bodyBorder: true,
            title: 'GİRİŞ YAP',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    height: 153,
                    items: [
                        {
                            xtype: 'panel',
                            border: false,
                            height: 142,
                            items: [
                                {
                                    xtype: 'image',
                                    margin: '20 0 0 0',
                                    width: 350,
                                    src: 'img/header.png'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 0.7,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    height: 44,
                                    margin: '20 5 0 0',
                                    width: 141,
                                    icon: 'img/student.png',
                                    text: 'ÖĞRENCİ GİRİŞİ',
                                    listeners: {
                                        click: 'onStudentLoginButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 44,
                                    margin: '20 0 0 5',
                                    width: 141,
                                    icon: 'img/teacher.png',
                                    text: 'AKADEMİSYEN GİRİŞİ',
                                    listeners: {
                                        click: 'onStudentLoginButtonClick1'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});