/*
 * File: app/view/loginPageViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.loginPageViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginpage',

    onStudentLoginButtonClick: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();

        var studentLoginPageView = Ext.create('StudentManagementSystem.view.studentLoginPage',
            {
                title : ''
                //class_no : refs.txtClass.getValue()
            }
            );

        var wind=Ext.create('Ext.Window',{
            itemId:'studentLoginPage',
            items:[studentLoginPageView],
            title:'ÖĞRENCİ GİRİŞİ',
            modal:true,
            closeAction:'destroy',
            resizable:false,
            closable: true,
            draggable: false,
            listeners:{
                'close':function(win){
                    studentLoginPageView.close();
                }
            }
        });
        wind.show();

        /* beni hatırla için
        if(Ext.getCmp('checkOgrenci').getValue() === true){
        Ext.getCmp('setNo').setValue('5');
        Ext.getCmp('setParola').setValue('5');
        }
        */

    },

    onStudentLoginButtonClick1: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();

        var teacherLoginPageView = Ext.create('StudentManagementSystem.view.teacherLoginPage',
            {
                title : ''
                //class_no : refs.txtClass.getValue()
            }
            );

        var wind=Ext.create('Ext.Window',{
            itemId:'teacherLoginPage',
            items:[teacherLoginPageView],
            title:'AKADEMİSYEN GİRİŞİ',
            modal:true,
            closeAction:'destroy',
            resizable:false,
            closable: true,
            draggable: false,
            listeners:{
                'close':function(win){
                    teacherLoginPageView.close();
                }
            }
        });
        wind.show();
    }

});
