/*
 * File: app/view/mesajGonderOgretmenPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.mesajGonderOgretmenPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mesajgonderogretmenpage',

    requires: [
        'StudentManagementSystem.view.mesajGonderPageViewModel1',
        'StudentManagementSystem.view.mesajGonderPageViewController1',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check'
    ],

    controller: 'mesajgonderogretmenpage',
    viewModel: {
        type: 'mesajgonderogretmenpage'
    },
    height: 346,
    width: 550,
    collapsed: false,
    collapsible: false,
    title: 'Mesaj',
    titleCollapse: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    height: 467,
                    title: 'MESAJ GÖNDER',
                    items: [
                        {
                            xtype: 'container',
                            margin: '20 0 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    reference: 'sinif',
                                    height: 30,
                                    readOnly: false,
                                    emptyText: 'SINIF SEÇ',
                                    displayField: 'lesId',
                                    store: 'CourseStore',
                                    valueField: 'lesId'
                                },
                                {
                                    xtype: 'combobox',
                                    reference: 'numara',
                                    height: 30,
                                    margin: '0 0 0 30',
                                    width: 240,
                                    emptyText: 'ÖĞRENCİ NUMARASI İLE GÖNDER',
                                    displayField: 'txtStudentNo',
                                    store: 'UserStore',
                                    valueField: 'txtStudentNo'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 215,
                            margin: '50 0 0 0',
                            items: [
                                {
                                    xtype: 'textareafield',
                                    reference: 'mesaj',
                                    height: 126,
                                    margin: '0 0 0 20',
                                    width: 507,
                                    labelAlign: 'right',
                                    value: 'bu mesaj deneme amacıyla yazılmıştır.',
                                    emptyText: 'MESAJ'
                                },
                                {
                                    xtype: 'button',
                                    height: 37,
                                    margin: '10 0 0 445',
                                    width: 82,
                                    text: 'ÖNİZLE',
                                    listeners: {
                                        click: 'onOnizleButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'MESAJ OKU',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            width: 546,
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    reference: 'mesajGrid',
                                    border: false,
                                    height: 386,
                                    id: 'mesajGrid1',
                                    width: 544,
                                    store: 'MesajStore',
                                    viewConfig: {
                                        height: 450,
                                        id: 'mesajGridR1',
                                        width: 397,
                                        listeners: {
                                            rowdblclick: 'onMesajGridRRowDblClick1'
                                        }
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'unvan',
                                            id: 'unvan1',
                                            width: 83,
                                            dataIndex: 'unvan',
                                            text: 'ÜNVAN'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'ad',
                                            width: 122,
                                            dataIndex: 'ad',
                                            text: 'AD SOYAD'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'mesaj',
                                            width: 180,
                                            dataIndex: 'mesaj',
                                            text: 'MESAJ'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'tarih',
                                            width: 79,
                                            dataIndex: 'tarih',
                                            text: 'TARİH'
                                        },
                                        {
                                            xtype: 'checkcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if(value === 0) {
                                                    metaData.style = "height:20px;background-color:green;";
                                                } else {
                                                    metaData.style = "height:20px;background-color:black;";
                                                }
                                                return value;
                                            },
                                            reference: 'check',
                                            width: 60,
                                            dataIndex: 'check',
                                            text: 'OKUNDU'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});