/*
 * File: app/view/mesajGonderPageViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.mesajGonderPageViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mesajgonderpage',

    onOnizleButtonClick: function(button, e, eOpts) {

        var controller=this;
        var refs = controller.getReferences();
        var bosGirdi = "";

        if (refs.adSoyad.value === bosGirdi || refs.telefonNo.value === bosGirdi || refs.tcNo.value === bosGirdi ||
        refs.il.value === bosGirdi || refs.ilce.value === bosGirdi || refs.adres.value === bosGirdi || refs.mesaj.value === bosGirdi){
            Ext.Msg.alert('HATA', 'Lütfen Boş Alanları Doldurunuz !');
        }
        else if(refs.tcNo.value.length != 11 || refs.tcNo.value % 1 !== 0 || refs.tcNo.value.includes('.')){
            Ext.Msg.alert('HATA', 'TC Kimlik Numarası 11 Rakamdan Oluşmalıdır !');
        }
        /*else if(refs.mesaj.value.length > 200){
        Ext.Msg.alert('HATA', 'Mesajınız 200 Karakterden Az Olmalıdır !');
        }*/
        else if(!(/^[a-zA-Z _]*$/.test(refs.adSoyad.value)) || !(/^[a-zA-Z _]*$/.test(refs.il.value)) || !(/^[a-zA-Z _]*$/.test(refs.ilce.value))){
            Ext.Msg.alert('HATA', 'Ad-Soyad, İl ve İlçede Sadece Harf ve Boşluk Bulunabilir !');
        }
        else if(refs.telefonNo.value.length != 10 || !(/^[0-9]*$/.test(refs.telefonNo.value))){
            Ext.Msg.alert('HATA', 'Telefon Numaranız 10 Rakamdan Oluşmalı ve Başında 0 Bulunmamalıdır !');
        }

        else{

            var konu = "";
            if (refs.rb1.value === true){
                konu = refs.rb1.boxLabel;
            }
            else if (refs.rb2.value === true){
                konu = refs.rb2.boxLabel;
            }
            else if (refs.rb3.value === true){
                konu = refs.rb3.boxLabel;
            }
            else {
                konu = refs.rb4.boxLabel;
            }
            var myForm = new Ext.form.Panel({
                width: 300,
                height: 350,
                title: 'Bilgiler',
                modal: true,
                floating: true,
                closable : true,
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                items: [
                {
                    xtype: 'container',
                    flex: 0.7,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                    {
                        xtype: 'label',
                        margin: '15 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'AD SOYAD: ' + refs.adSoyad.value.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() +
                        txt.substr(1).toLowerCase();})
                    },
                    {
                        xtype: 'label',
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'TELEFON NO: ' + parseInt(refs.telefonNo.value)
                    },
                    {
                        xtype: 'label',
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'TC KİMLİK NO: ' + parseInt(refs.tcNo.value)
                    },
                    {
                        xtype: 'label',
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'İL: ' + refs.il.value.toUpperCase()
                    },
                    {
                        xtype: 'label',
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'İLÇE: ' + refs.ilce.value.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() +
                        txt.substr(1).toLowerCase();})
                    },
                    {
                        xtype: 'label',
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'ADRES: ' + refs.adres.value.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() +
                        txt.substr(1).toLowerCase();})
                    },
                    {
                        xtype: 'label',
                        readOnly: true,
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'MESAJ KONUSU: ' + konu
                    },
                    {
                        xtype: 'label',
                        readOnly: true,
                        margin: '10 0 0 0',
                        style: 'font-weight:bold;',
                        text: 'MESAJ: ' + refs.mesaj.value
                    }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 0.3,
                    layout: {
                        type: 'vbox',
                        align: 'start',
                        pack: 'start'
                    },
                    items: [
                    {
                        xtype: 'button',
                        reference: 'gonderButton',
                        margin: '50 0 0 110',
                        height: 32,
                        text: 'GÖNDER',
                        listeners: {
                            click: 'onGonderButtonClick'
                        }
                    }
                    ]
                }
                ]


            });
            myForm.show();
        }
    },

    onMesajGridRRowDblClick: function(tableview, record, tr, rowIndex, e, eOpts) {
        var controller = this;
        var refs = controller.getReferences();
        var myForm = new Ext.form.Panel({
            width: 350,
            height: 300,
            title: 'MESAJ',
            modal: true,
            floating: true,
            closable : true,
            items: [
            {
                xtype: 'container',
                flex: 0.3,
                margin: '10 0 0 5',
                layout: {
                    type: 'vbox',
                    pack: 'center'
                },
                items: [
                {
                    xtype: 'label',
                    width: 350,
                    margin: '5 0 0 0',
                    style: 'font-weight: bold;',
                    text: 'AD SOYAD: ' + refs.mesajGrid.store.data.items[rowIndex].data.unvan + refs.mesajGrid.store.data.items[rowIndex].data.ad
                },
                {
                    xtype: 'label',
                    width: 350,
                    margin: '5 0 0 0',
                    style: 'font-weight: bold;',
                    text: 'TARİH: ' + refs.mesajGrid.store.data.items[rowIndex].data.tarih
                },
                {
                    xtype: 'label',
                    width: 350,
                    margin: '20 0 0 0',
                    text: 'MESAJ: ' + refs.mesajGrid.store.data.items[rowIndex].data.mesaj
                }
                ]
            }]

        });
        myForm.show();
        //Ext.MessageBox.alert(refs.courseList.store.data.items[rowIndex].data.lesName,refs.courseList.store.data.items[rowIndex].data.lesTeacher);
    }

});
