/*
 * File: app/view/mesajGonderPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.mesajGonderPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mesajgonderpage',

    requires: [
        'StudentManagementSystem.view.mesajGonderPageViewModel',
        'StudentManagementSystem.view.mesajGonderPageViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check'
    ],

    controller: 'mesajgonderpage',
    viewModel: {
        type: 'mesajgonderpage'
    },
    height: 561,
    width: 550,
    collapsed: false,
    collapsible: false,
    title: 'Mesaj',
    titleCollapse: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'MESAJ GÖNDER',
                    items: [
                        {
                            xtype: 'container',
                            margin: '20 0 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    height: 30,
                                    width: 366,
                                    fieldLabel: 'Akademisyen Seç',
                                    displayField: 'name',
                                    store: 'TeacherStore',
                                    valueField: 'name'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 217,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 319,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            reference: 'adSoyad',
                                            height: 37,
                                            margin: '30 0 0 20',
                                            width: 220,
                                            labelAlign: 'right',
                                            value: 'cihan selim',
                                            emptyText: 'AD SOYAD'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'telefonNo',
                                            height: 37,
                                            margin: '10 0 0 20',
                                            width: 220,
                                            labelAlign: 'right',
                                            value: 5387229626,
                                            emptyText: 'TELEFON NUMARASI'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'tcNo',
                                            height: 37,
                                            margin: '10 0 0 20',
                                            padding: '0 0 10 0',
                                            width: 220,
                                            labelAlign: 'right',
                                            value: 59767413776,
                                            emptyText: 'TC KİMLİK NUMARASI'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: '0 0 0 25',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            reference: 'il',
                                            height: 37,
                                            margin: '30 0 0 20',
                                            width: 220,
                                            labelAlign: 'right',
                                            value: 'trabzon',
                                            emptyText: 'İL'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'ilce',
                                            height: 37,
                                            margin: '10 0 0 20',
                                            width: 220,
                                            labelAlign: 'right',
                                            value: 'yomra',
                                            emptyText: 'İLÇE'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'adres',
                                            height: 37,
                                            margin: '10 0 0 20',
                                            width: 220,
                                            labelAlign: 'right',
                                            value: 'sancak mah. rize cad. sahil sit. b doğu blok no:4',
                                            emptyText: 'ADRES'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 215,
                            items: [
                                {
                                    xtype: 'label',
                                    margin: '0 0 0 20',
                                    text: 'Mesaj Konusu: '
                                },
                                {
                                    xtype: 'radiogroup',
                                    margin: '0 0 0 45',
                                    padding: '0 0 10 0',
                                    width: 500,
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            reference: 'rb1',
                                            name: 'Radio1',
                                            boxLabel: 'Ders Kaydı'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            reference: 'rb2',
                                            name: 'Radio1',
                                            boxLabel: 'Staj'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            reference: 'rb3',
                                            name: 'Radio1',
                                            boxLabel: 'Erasmus'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            reference: 'rb4',
                                            name: 'Radio1',
                                            boxLabel: 'Diğer'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'mesaj',
                                    height: 126,
                                    margin: '0 0 0 20',
                                    width: 507,
                                    labelAlign: 'right',
                                    value: 'bu mesaj deneme amacıyla yazılmıştır.',
                                    readOnly: false,
                                    emptyText: 'MESAJ'
                                },
                                {
                                    xtype: 'button',
                                    height: 37,
                                    margin: '10 0 0 445',
                                    width: 82,
                                    text: 'ÖNİZLE',
                                    listeners: {
                                        click: 'onOnizleButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'MESAJ OKU',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            width: 546,
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    reference: 'mesajGrid',
                                    border: false,
                                    height: 386,
                                    id: 'mesajGrid',
                                    width: 544,
                                    store: 'MesajStore',
                                    viewConfig: {
                                        height: 450,
                                        id: 'mesajGridR',
                                        width: 397,
                                        listeners: {
                                            rowdblclick: 'onMesajGridRRowDblClick'
                                        }
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'unvan',
                                            id: 'unvan',
                                            width: 83,
                                            dataIndex: 'unvan',
                                            text: 'ÜNVAN'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'ad',
                                            width: 122,
                                            dataIndex: 'ad',
                                            text: 'AD SOYAD'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'mesaj',
                                            width: 180,
                                            dataIndex: 'mesaj',
                                            text: 'MESAJ'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            reference: 'tarih',
                                            width: 79,
                                            dataIndex: 'tarih',
                                            text: 'TARİH'
                                        },
                                        {
                                            xtype: 'checkcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if(value === 0) {
                                                    metaData.style = "height:20px;background-color:green;";
                                                } else {
                                                    metaData.style = "height:20px;background-color:black;";
                                                }
                                                return value;
                                            },
                                            reference: 'check',
                                            width: 60,
                                            dataIndex: 'check',
                                            text: 'OKUNDU'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});