/*
 * File: app/view/ogrenciNotPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.ogrenciNotPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ogrencinotpage',

    requires: [
        'StudentManagementSystem.view.ogrenciNotPageViewModel',
        'StudentManagementSystem.view.ogrenciNotPageViewController',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    controller: 'ogrencinotpage',
    viewModel: {
        type: 'ogrencinotpage'
    },
    reference: 'ogrenciNotPage',
    height: 350,
    itemId: 'ogrenciNotPage',
    width: 927,
    title: 'ÖĞRENCİLER',

    items: [
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'combobox',
                    height: 32,
                    margin: '10 0 10 10',
                    width: 246,
                    emptyText: 'DERS SEÇİNİZ',
                    displayField: 'lesName',
                    store: 'CourseStore',
                    valueField: 'lesName'
                },
                {
                    xtype: 'gridpanel',
                    reference: 'notGrid',
                    border: false,
                    height: 322,
                    store: 'UserStore',
                    viewConfig: {
                        reference: 'notGrid',
                        listeners: {
                            celldblclick: 'onTableCellDblClick'
                        }
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtId',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtName',
                            text: 'AD'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtSurname',
                            text: 'SOYAD'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtIdentifierNo',
                            text: 'TC NO'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtStudentNo',
                            text: 'ÖĞRENCİ NO'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtFaculty',
                            text: 'FAKÜLTE'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'txtDepartment',
                            text: 'BÖLÜM'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 72,
                            dataIndex: 'txtClass',
                            text: 'SINIF'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 122,
                            dataIndex: 'txtActiveSeason',
                            text: 'AKTİF YIL'
                        }
                    ]
                }
            ]
        }
    ]

});