/*
 * File: app/view/ogrenciNotPageViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.ogrenciNotPageViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.ogrencidevamsizlikpage',

    onTableCellDblClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var refs = this.getReferences();

        var myForm = new Ext.form.Panel({
            title: 'DEVAMSIZLIK',
            floating: true,
            closable : true,
            modal: true,
            height: 172,
            width: 637,

            items: [
            {
                xtype: 'container',
                layout: {
                    type: 'hbox',
                    align: 'stretch'
                },
                items: [
                {
                    xtype: 'container',
                    margin: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                    {
                        xtype: 'label',
                        style: 'font-weight: bold;',
                        text: 'AD: ' + refs.devamGrid.store.data.items[rowIndex].data.txtName
                    },
                    {
                        xtype: 'label',
                        style: 'font-weight: bold;',
                        text: 'SOYAD: ' + refs.devamGrid.store.data.items[rowIndex].data.txtSurname
                    },
                    {
                        xtype: 'label',
                        style: 'font-weight: bold;',
                        text: 'ÖĞRENCİ NUMARASI:' + refs.devamGrid.store.data.items[rowIndex].data.txtStudentNo
                    }
                    ]
                }
                ]
            },
            {
                xtype: 'container',
                items: [
                {
                    xtype: 'panel',
                    collapsible: true,
                    title: 'DEVAMSIZLIK',
                    titleCollapse: true,
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'end'
                    },
                    items: [
                    {
                        xtype: 'textfield',
                        reference: 'devamsizlik',
                        height: 32,
                        margin: '20 10 0 0',
                        fieldLabel: '',
                        emptyText: 'DEVAMSIZLIK'
                    },
                    {
                        xtype: 'button',
                        height: 34,
                        margin: '0 24 0 0',
                        width: 100,
                        text: 'KAYDET',
                        listeners: {
                            click: 'onDevamsizlikButtonClick'
                        }
                    }
                    ]
                }
                ]
            },
            {
                xtype: 'container'
            }
            ]
        });
        myForm.show();
    }

});
