/*
 * File: app/view/SilinebilirViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.SilinebilirViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.silinebilir',

    onDersProgPanelAfterRender: function(component, eOpts) {
        /*
        if (Ext.isDefined(component.class_no)){
        if (component.class_no === 1){
        tabs.setActiveTab(0);
        }
        if (component.class_no === 2){
        tabs.setActiveTab(1);
        }
        if (component.class_no === 3){
        tabs.setActiveTab(2);
        }
        else{
        tabs.setActiveTab(3);
        }
        }
        */
    }

});
