/*
 * File: app/view/studentLoginPageViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.studentLoginPageViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.studentloginpage',

    onOgrenciGirisButonuClick: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        var bosGirdi = "";
        var userList = [];
        var passList = [];

        for (i = 0 ; i < Ext.StoreMgr.lookup("UserStore").data.length; i++){
            userList.push(Ext.StoreMgr.lookup("UserStore").data.items[i].data.txtStudentNo);
            passList.push(Ext.StoreMgr.lookup("UserStore").data.items[i].data.txtIdentifierNo);
        }

        if(refs.ogrenciNo.value === bosGirdi)
        {
            Ext.Msg.alert('HATA', 'Kullanıcı Adı Boş Geçilemez.');
        }

        else if(refs.ogrenciParola.value === bosGirdi)
        {
            Ext.Msg.alert('HATA', 'Parola Boş Geçilemez.');
        }

        else if(userList.includes(refs.ogrenciNo.value) && passList.includes(refs.ogrenciParola.value))
        {
            //olması gereken
            //refs.ogrenciNo.value === userList[i][0] || refs.ogrenciParola.value === userList[i][1]

            //remember me starts

            if (refs.checkOgrenci.value === true) {
                localStorage.username = Ext.getCmp('setNo').getValue();
                localStorage.password = Ext.getCmp('setParola').getValue();
            } else {
                localStorage.removeItem('username');
                localStorage.removeItem('password');
            }
            //remember me ends

            var indexPageView = Ext.create('StudentManagementSystem.view.indexPage',
                {
                    title : '',
                    username : refs.ogrenciNo.getValue()
                }
                );

            var wind=Ext.create('Ext.Window',{
                width: 1440,
                height: 900,
                itemId:'indexPage',
                items:[indexPageView],
                title:'ÜNİVERSİTE | ÖĞRENCİ BİLGİ SİSTEMİ',
                modal:false,
                closeAction:'destroy',
                resizable:false,
                closable: false,
                draggable: false,
                listeners:{
                    'close':function(win){
                        indexPageView.close();
                    }
                }
            });
            wind.show();
        }

        else
        {
            Ext.Msg.alert('HATA', 'Kullanıcı Adı ve/veya Parola Yanlış Girildi.');
        }

    },

    onPanelAfterRender: function(component, eOpts) {
        Ext.getCmp('setNo').setValue(localStorage.username);
        Ext.getCmp('setParola').setValue(localStorage.password);
    }

});
