/*
 * File: app/view/studentLoginPageViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.studentLoginPageViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.teacherloginpage',

    onTeacherGirisButonuClick: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        var bosGirdi = "";
        var userList = [];
        var passList = [];

        for (i = 0 ; i < Ext.StoreMgr.lookup("TeacherStore").data.length; i++){
            userList.push(Ext.StoreMgr.lookup("TeacherStore").data.items[i].data.login_id);
            passList.push(Ext.StoreMgr.lookup("TeacherStore").data.items[i].data.login_id);
        }

        if(refs.akademisyenNo.value === bosGirdi)
        {
            Ext.Msg.alert('HATA', 'Kullanıcı Adı Boş Geçilemez.');
        }

        else if(refs.akademisyenParola.value === bosGirdi)
        {
            Ext.Msg.alert('HATA', 'Parola Boş Geçilemez.');
        }

        else if(userList.includes(refs.akademisyenNo.value) && passList.includes(refs.akademisyenParola.value))
        {
            //remember me starts

            if (refs.checkAkademisyen.value === true) {
                localStorage.usernameA = Ext.getCmp('setNoA').getValue();
                localStorage.passwordA = Ext.getCmp('setParolaA').getValue();
            } else {
                localStorage.removeItem('usernameA');
                localStorage.removeItem('passwordA');
            }

            //remember me ends
            var indexTeacherPageView = Ext.create('StudentManagementSystem.view.indexTeacherPage',
                {
                    title : '',
                    username : refs.akademisyenNo.getValue()
                }
                );

            var wind=Ext.create('Ext.Window',{
                width: 1440,
                height: 900,
                itemId:'indexTeacherPage',
                items:[indexTeacherPageView],
                title:'ÜNİVERSİTE | ÖĞRENCİ BİLGİ SİSTEMİ',
                modal:false,
                closeAction:'destroy',
                resizable:false,
                closable: false,
                draggable: false,
                listeners:{
                    'close':function(win){
                        indexTeacherPageView.close();
                    }
                }
            });
            wind.show();
        }

        else
        {
            Ext.Msg.alert('HATA', 'Kullanıcı Adı ve/veya Parola Yanlış Girildi.');
        }

    },

    onPanelAfterRender: function(component, eOpts) {
        Ext.getCmp('setNoA').setValue(localStorage.usernameA);
        Ext.getCmp('setParolaA').setValue(localStorage.passwordA);
    }

});
