/*
 * File: app/view/studentLoginPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.studentLoginPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.studentloginpage',

    requires: [
        'StudentManagementSystem.view.studentLoginPageViewModel',
        'StudentManagementSystem.view.studentLoginPageViewController',
        'Ext.container.Container',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    controller: 'studentloginpage',
    viewModel: {
        type: 'studentloginpage'
    },
    height: 229,
    width: 320,
    title: 'ÖĞRENCİ GİRİŞİ',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            items: [
                {
                    xtype: 'textfield',
                    reference: 'ogrenciNo',
                    height: 40,
                    id: 'setNo',
                    margin: '30 0 0 0',
                    width: 301,
                    labelAlign: 'right',
                    emptyText: 'Öğrenci Numarası',
                    value: 5
                },
                {
                    xtype: 'textfield',
                    reference: 'ogrenciParola',
                    height: 40,
                    id: 'setParola',
                    itemId: 'ogrenciParola',
                    margin: '5 0 0 0',
                    width: 301,
                    labelAlign: 'right',
                    inputType: 'password',
                    emptyText: 'Parola',
                    value: 5
                },
                {
                    xtype: 'checkboxfield',
                    reference: 'checkOgrenci',
                    id: 'checkOgrenci',
                    margin: '5 0 0 0',
                    boxLabel: 'Beni Hatırla'
                },
                {
                    xtype: 'button',
                    reference: 'ogrenciGirisButonu',
                    height: 40,
                    itemId: 'ogrenciGirisButonu',
                    margin: '8 0 0 0',
                    width: 300,
                    text: 'GİRİŞ YAP',
                    listeners: {
                        click: 'onOgrenciGirisButonuClick'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});
