/*
 * File: app/view/teacherLoginPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.teacherLoginPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.teacherloginpage',

    requires: [
        'StudentManagementSystem.view.studentLoginPageViewModel1',
        'StudentManagementSystem.view.studentLoginPageViewController1',
        'Ext.container.Container',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    controller: 'teacherloginpage',
    viewModel: {
        type: 'teacherloginpage'
    },
    height: 250,
    width: 320,
    title: 'AKADEMİSYEN GİRİŞİ',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            items: [
                {
                    xtype: 'textfield',
                    reference: 'akademisyenNo',
                    height: 40,
                    id: 'setNoA',
                    margin: '30 0 0 0',
                    width: 301,
                    labelAlign: 'right',
                    emptyText: 'Akademisyen ID'
                },
                {
                    xtype: 'textfield',
                    reference: 'akademisyenParola',
                    height: 40,
                    id: 'setParolaA',
                    margin: '5 0 0 0',
                    width: 301,
                    labelAlign: 'right',
                    inputType: 'password',
                    emptyText: 'Parola'
                },
                {
                    xtype: 'checkboxfield',
                    reference: 'checkAkademisyen',
                    margin: '5 0 0 0',
                    boxLabel: 'Beni Hatırla'
                },
                {
                    xtype: 'button',
                    reference: 'ogrenciGirisButonu',
                    height: 40,
                    itemId: 'ogrenciGirisButonu',
                    margin: '8 0 0 0',
                    width: 300,
                    text: 'GİRİŞ YAP',
                    listeners: {
                        click: 'onTeacherGirisButonuClick'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});