/*
 * File: app/view/transkriptPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.transkriptPage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.transkriptpage',

    requires: [
        'StudentManagementSystem.view.transkriptPageViewModel',
        'StudentManagementSystem.view.transkriptPageViewController',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.panel.Panel',
        'Ext.form.Label'
    ],

    controller: 'transkriptpage',
    viewModel: {
        type: 'transkriptpage'
    },
    height: 569,
    width: 990,
    title: 'Transkript Senaryosu',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1.2,
            style: 'background-color:#F5F5F5;',
            items: [
                {
                    xtype: 'container',
                    margin: 20,
                    width: 537,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'dersAdi1',
                            height: 40,
                            width: 150,
                            emptyText: 'Ders Adı (isteğe bağlı)'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'harf1',
                            margin: '0 0 0 20',
                            readOnly: false,
                            emptyText: 'Harf Notu',
                            displayField: 'harf',
                            queryMode: 'local',
                            store: 'TranskriptStore',
                            valueField: 'deger'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'kredi1',
                            margin: '0 0 0 20',
                            emptyText: 'Kredi Sayısı',
                            displayField: 'kredi',
                            queryMode: 'local',
                            store: 'TKrediStore',
                            valueField: 'kredi'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            icon: 'img/sil.png',
                            listeners: {
                                click: 'onSilButton1Click'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: 20,
                    width: 542,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'dersAdi2',
                            height: 40,
                            width: 150,
                            emptyText: 'Ders Adı (isteğe bağlı)'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'harf2',
                            margin: '0 0 0 20',
                            emptyText: 'Harf Notu',
                            displayField: 'harf',
                            queryMode: 'local',
                            store: 'TranskriptStore',
                            valueField: 'deger'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'kredi2',
                            margin: '0 0 0 20',
                            emptyText: 'Kredi Sayısı',
                            displayField: 'kredi',
                            queryMode: 'local',
                            store: 'TKrediStore',
                            valueField: 'kredi'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            icon: 'img/sil.png',
                            listeners: {
                                click: 'onSilButton1Click1'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: 20,
                    width: 544,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'dersAdi3',
                            height: 40,
                            width: 150,
                            emptyText: 'Ders Adı (isteğe bağlı)'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'harf3',
                            margin: '0 0 0 20',
                            emptyText: 'Harf Notu',
                            displayField: 'harf',
                            queryMode: 'local',
                            store: 'TranskriptStore',
                            valueField: 'deger'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'kredi3',
                            margin: '0 0 0 20',
                            emptyText: 'Kredi Sayısı',
                            displayField: 'kredi',
                            queryMode: 'local',
                            store: 'TKrediStore',
                            valueField: 'kredi'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            icon: 'img/sil.png',
                            listeners: {
                                click: 'onSilButton1Click11'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: 20,
                    width: 551,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'dersAdi4',
                            height: 40,
                            width: 150,
                            emptyText: 'Ders Adı (isteğe bağlı)'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'harf4',
                            margin: '0 0 0 20',
                            emptyText: 'Harf Notu',
                            displayField: 'harf',
                            queryMode: 'local',
                            store: 'TranskriptStore',
                            valueField: 'deger'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'kredi4',
                            margin: '0 0 0 20',
                            emptyText: 'Kredi Sayısı',
                            displayField: 'kredi',
                            queryMode: 'local',
                            store: 'TKrediStore',
                            valueField: 'kredi'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            icon: 'img/sil.png',
                            listeners: {
                                click: 'onSilButton1Click111'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: 20,
                    width: 546,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'dersAdi5',
                            height: 40,
                            width: 150,
                            emptyText: 'Ders Adı (isteğe bağlı)'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'harf5',
                            margin: '0 0 0 20',
                            emptyText: 'Harf Notu',
                            displayField: 'harf',
                            queryMode: 'local',
                            store: 'TranskriptStore',
                            valueField: 'deger'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'kredi5',
                            margin: '0 0 0 20',
                            emptyText: 'Kredi Sayısı',
                            displayField: 'kredi',
                            queryMode: 'local',
                            store: 'TKrediStore',
                            valueField: 'kredi'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            icon: 'img/sil.png',
                            listeners: {
                                click: 'onSilButton1Click1111'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: 20,
                    width: 547,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'dersAdi6',
                            height: 40,
                            width: 150,
                            emptyText: 'Ders Adı (isteğe bağlı)'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'harf6',
                            margin: '0 0 0 20',
                            emptyText: 'Harf Notu',
                            displayField: 'harf',
                            queryMode: 'local',
                            store: 'TranskriptStore',
                            valueField: 'deger'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'kredi6',
                            margin: '0 0 0 20',
                            emptyText: 'Kredi Sayısı',
                            displayField: 'kredi',
                            queryMode: 'local',
                            store: 'TKrediStore',
                            valueField: 'kredi'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 20',
                            icon: 'img/sil.png',
                            listeners: {
                                click: 'onSilButton1Click11111'
                            }
                        }
                    ]
                },
                {
                    xtype: 'button',
                    reference: 'hesaplaButton',
                    height: 40,
                    itemId: 'hesaplaButton',
                    margin: '0 0 0 450',
                    text: 'HESAPLA',
                    listeners: {
                        click: 'onTranskriptButtonClick'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            flex: 0.9,
            items: [
                {
                    xtype: 'panel',
                    height: 708,
                    margin: '',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            margin: '50 0 0 0',
                            style: 'font-weight:bold;',
                            text: 'ORTALAMANIZ'
                        },
                        {
                            xtype: 'label',
                            reference: 'ortalama',
                            itemId: 'ortalama',
                            margin: '20 0 0 0',
                            style: 'font-weight:bold;font-size:20px;',
                            text: '-'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margin: '80 0 20 0',
                                            style: 'font-weight:bold;',
                                            text: 'DERS ADI'
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'ders_adi1',
                                            margin: '10 0 0 0',
                                            width: 210,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'ders_adi2',
                                            margin: '20 0 0 0',
                                            width: 210,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'ders_adi3',
                                            margin: '20 0 0 0',
                                            width: 210,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'ders_adi4',
                                            margin: '20 0 0 0',
                                            width: 210,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'ders_adi5',
                                            margin: '20 0 0 0',
                                            width: 210,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            flex: 1,
                                            reference: 'ders_adi6',
                                            margin: '20 0 0 0',
                                            width: 210,
                                            text: ''
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margin: '80 0 20 0',
                                            style: 'font-weight:bold;',
                                            text: 'HARF NOTU'
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'harf_notu1',
                                            margin: '10 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'harf_notu2',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'harf_notu3',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'harf_notu4',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'harf_notu5',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            flex: 1,
                                            reference: 'harf_notu6',
                                            margin: '20 0 0 0',
                                            text: ''
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: '0 0 0 30',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margin: '80 0 20 0',
                                            style: 'font-weight:bold;',
                                            text: 'KREDİ'
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'kredi_1',
                                            margin: '10 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'kredi_2',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'kredi_3',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'kredi_4',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            reference: 'kredi_5',
                                            margin: '20 0 0 0',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            flex: 1,
                                            reference: 'kredi_6',
                                            margin: '20 0 0 0',
                                            text: ''
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});