/*
 * File: app/view/transkriptPageViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StudentManagementSystem.view.transkriptPageViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.transkriptpage',

    onSilButton1Click: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        refs.harf1.clearValue();
        refs.kredi1.clearValue();
    },

    onSilButton1Click1: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        refs.harf2.clearValue();
        refs.kredi2.clearValue();
    },

    onSilButton1Click11: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        refs.harf3.clearValue();
        refs.kredi3.clearValue();
    },

    onSilButton1Click111: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        refs.harf4.clearValue();
        refs.kredi4.clearValue();
    },

    onSilButton1Click1111: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        refs.harf5.clearValue();
        refs.kredi5.clearValue();
    },

    onSilButton1Click11111: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();
        refs.harf6.clearValue();
        refs.kredi6.clearValue();
    },

    onTranskriptButtonClick: function(button, e, eOpts) {
        var controller=this;
        var refs = controller.getReferences();

        var all_list = [refs.kredi1.lastValue,refs.kredi2.lastValue,refs.kredi3.lastValue,
            refs.kredi4.lastValue,refs.kredi5.lastValue,refs.kredi6.lastValue,
            refs.harf1.lastValue,refs.harf2.lastValue,refs.harf3.lastValue,
            refs.harf4.lastValue,refs.harf5.lastValue,refs.harf6.lastValue];

        var kredi_list = [refs.kredi1.lastValue,refs.kredi2.lastValue,refs.kredi3.lastValue,
            refs.kredi4.lastValue,refs.kredi5.lastValue,refs.kredi6.lastValue];

        var harf_list = [refs.harf1.lastValue,refs.harf2.lastValue,refs.harf3.lastValue,
            refs.harf4.lastValue,refs.harf5.lastValue,refs.harf6.lastValue];
        var toplam_kredi = 0;
        var toplam = 0;

        for (var i =0; i<all_list.length/2; i++){
            //bos bırakıldığında 0 almak için
            if (all_list[i] === "" || all_list[i+6] === ""){
                all_list[i] = 0;
                all_list[i+6] = 0;
            }
            //deger ve kredi çarpım toplamı
            else{
                toplam = toplam + (all_list[i+6] * all_list[i]);
                toplam_kredi = toplam_kredi + (kredi_list[i] * 1);

            }

        }

        var sonuc = toplam / toplam_kredi;
        refs.ortalama.setText(sonuc);

        //Ders adı Yazdırma
        var ders_yaz_list = [refs.ders_adi1,refs.ders_adi2,refs.ders_adi3,refs.ders_adi4,refs.ders_adi5,refs.ders_adi6];
        var harf_yaz_list = [refs.harf_notu1,refs.harf_notu2,refs.harf_notu3,refs.harf_notu4,refs.harf_notu5,refs.harf_notu6];
        var kredi_yaz_list = [refs.kredi_1,refs.kredi_2,refs.kredi_3,refs.kredi_4,refs.kredi_5,refs.kredi_6];

        var ders_adi_list = [refs.dersAdi1.lastValue,refs.dersAdi2.lastValue,refs.dersAdi3.lastValue,refs.dersAdi4.lastValue,
            refs.dersAdi5.lastValue,refs.dersAdi6.lastValue];
        for(var i = 0; i < ders_yaz_list.length;i++){
            ders_yaz_list[i].setText(ders_adi_list[i]);
            harf_yaz_list[i].setText(harf_list[i]);
            kredi_yaz_list[i].setText(kredi_list[i]);
        }
    }

});
